version: '3.1'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: NodePessoa
      DB_USER: root
      DB_PASSWORD: ayrtondocker
    depends_on:
      - db
  db:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ayrtondocker
      MYSQL_DATABASE: NodePessoa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
